Name: 🐞 Build Debug APK
run-name: 🐞 Debug Build - ${{ github.actor }}

on:
  push:
    branches: [ "n" ]
  pull_request:
    branches: [ "n" ]
  workflow_dispatch:

jobs:
  debug-build:
    runs-on: ubuntu-latest
    steps:
      - name: 👨🏻‍💻 Checkout
        uses: actions/checkout@v4

      - name: ☕ Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"
          cache: gradle

      - name: 🤝 Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: ☎️ Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 🔥 Build Debug APK (arm64-v8a only)
        # 通过 Gradle 属性过滤架构，只构建 arm64-v8a
        run: ./gradlew assembleDebug -PabiFilters=arm64-v8a

      - name: 🚀 Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk-arm64-v8a
          # 通常 debug 包会在此路径，如果找不到，Gradle 会自动报错提示路径
          path: app/build/outputs/apk/debug/app-debug.apk
