name: 🐞 Build Debug APK
run-name: 🐞 Debug Build - ${{ github.actor }}

on:
  push:
    branches: [ "n" ]
  pull_request:
    branches: [ "n" ]
  workflow_dispatch:

jobs:
  debug-build:
    runs-on: ubuntu-latest

    steps:
      - name: ⏰ Set Timezone to Asia/Shanghai
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          echo "Current time: $(date)"

      - name: 👨🏻‍💻 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: ☕ Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"
          cache: gradle

      - name: 🤝 Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          gradle-version: wrapper

      - name: ☎️ Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 🔥 Build Debug APK with Gradle
        run: ./gradlew assembleDebug -Pversion=${{ github.ref_name }}

      - name: 📊 Locate Debug APKs
        id: locate_apks
        run: |
          debug_dir="app/build/outputs/apk/debug"
          # 仅查找 arm64-v8a 架构的包
          arm64_apk=$(find "$debug_dir" -name "*-arm64-v8a-*.apk" | head -n 1)
          
          echo "arm64_apk=$arm64_apk" >> $GITHUB_OUTPUT

      - name: 🚀 Upload Debug APK - arm64-v8a
        if: steps.locate_apks.outputs.arm64_apk != ''
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk-arm64-v8a
          path: ${{ steps.locate_apks.outputs.arm64_apk }}
